apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  namespace: kubecube-system
  labels:
    kubecube.io/app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      kubecube.io/app: audit
  template:
    metadata:
      labels:
        kubecube.io/app: audit
    spec:
      containers:
        - name: kubecube-audit
          image: hub.c.163.com/kubecube/audit:v1.0.0
          ports:
            - containerPort: 8888
          env:
            - name: JWT_SECRET
              value: "56F0D8DB90241C6E"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-nodeport
  namespace: kubecube-system
spec:
  type: NodePort
  selector:
    kubecube.io/app: audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: audit
  namespace: kubecube-system
spec:
  selector:
    kubecube.io/app: audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888