{{- if eq .Values.global.componentsEnable.audit "true" }}
apiVersion: v1
kind: Service
metadata:
  name: audit-nodeport
  namespace: {{ include "kubecube.namespace" . }}
spec:
  type: NodePort
  selector:
    kubecube.io/app: audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: audit
  namespace: {{ include "kubecube.namespace" . }}
spec:
  selector:
    kubecube.io/app: audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
---
{{- end }}