apiVersion: v1
kind: Service
metadata:
  name: kubecube
  namespace: kubecube-system
spec:
  selector:
    kubecube.io/app: kubecube
  ports:
    - name: http
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: https
      protocol: TCP
      port: 7443
      targetPort: 7443
    - name: webhook
      port: 9443
      targetPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: kubecube-nodeport
  namespace: kubecube-system
spec:
  type: NodePort
  selector:
    kubecube.io/app: kubecube
  ports:
    - name: http
      port: 7777
      targetPort: 7777
      nodePort: 30007
    - name: https
      port: 7443
      targetPort: 7443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecube
  namespace: kubecube-system
  labels:
    kubecube.io/app: kubecube
spec:
  replicas: {{ .Values.kubecube.replicas }}
  selector:
    matchLabels:
      kubecube.io/app: kubecube
  template:
    metadata:
      labels:
        kubecube.io/app: kubecube
    spec:
      containers:
        - name: kubecube
          image: {{ .Values.kubecube.image }}
          securityContext:
            runAsUser: 0
            privileged: true
          args:
            - -log-level={{ .Values.kubecube.args.logLevel }}
            - -secure-port={{ .Values.kubecube.args.securePort }}
            - -tls-cert=/etc/tls/tls.crt
            - -tls-key=/etc/tls/tls.key
            - -webhook-cert=/etc/tls
            - -webhook-server-port={{ .Values.kubecube.args.webhookServerPort }}
            - -leader-elect={{ .Values.kubecube.args.leaderElect }}
          env:
            - name: WARDEN_IMAGE
              value: {{ .Values.kubecube.env.wardenImage }}
            - name: WARDEN_INIT_IMAGE
              value: {{ .Values.kubecube.env.wardenInitImage }}
            - name: PIVOT_CUBE_CLUSTER_IP_SVC
              value: {{ .Values.kubecube.env.pivotCubeSvc }}
            - name: PIVOT_CUBE_HOST
              value: {{ .Values.kubecube.env.pivotCubeHost }}
            - name: JWT_SECRET
              value: {{ .Values.kubecube.env.jwtSecret }}
            - name: DEPENDENCE_JOB_IMAGE
              value: {{ .Values.kubecube.env.dependenceJobImage }}
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: cube-tls
              mountPath: "/etc/tls"
              readOnly: true
            - name: logs
              mountPath: "/etc/logs/cube"
            - name: helm-pkg
              mountPath: "/root/helmchartpkg"
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: cube-tls
          secret:
            secretName: cube-tls-secret
        - name: helm-pkg
          hostPath:
            path: /etc/cube/helm-pkg
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: /etc/cube/logs
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime