{{- if eq .Values.global.componentsEnable.kubecube "true" }}
apiVersion: v1
kind: Service
metadata:
  name: kubecube
  namespace: {{ template "kubecube.namespace" . }}
spec:
  selector:
    kubecube.io/app: kubecube
  ports:
    - name: http
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: https
      protocol: TCP
      port: 7443
      targetPort: 7443
    - name: webhook
      port: 9443
      targetPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: kubecube-nodeport
  namespace: {{ template "kubecube.namespace" . }}
spec:
  type: NodePort
  selector:
    kubecube.io/app: kubecube
  ports:
    - name: http
      port: 7777
      targetPort: 7777
      nodePort: 30007
    - name: https
      port: 7443
      targetPort: 7443
      nodePort: 30443
---
{{- end }}