{{- if eq .Values.global.componentsEnable.webconsole "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webconsole
  namespace: kubecube-system
  labels:
    kubecube.io/app: kubecube-webconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      kubecube.io/app: kubecube-webconsole
  template:
    metadata:
      labels:
        kubecube.io/app: kubecube-webconsole
    spec:
      {{- with .Values.webconsole.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webconsole.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webconsole.tolerations}}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: JWT_SECRET
              value: 56F0D8DB90241C6E
          name: kubecube-webconsole
          image: {{ .Values.webconsole.image.repository}}:{{ .Values.webconsole.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.webconsole.image.pullPolicy }}
          ports:
            - containerPort: 9081
          resources:
          {{- toYaml .Values.webconsole.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /leader
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
---
{{- end }}