# ordinary only has read authority under of
# bottom layer namespace used of RoleBinding.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reviewer-cluster
  annotations:
    kubecube.io/sync: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-reviewer-cluster: "true"
rules: []