# Default values for kubecube

kubecube:
  replicas: 1
  image: hub.c.163.com/kubecube/cube:v1.0.0

  args:
    logLevel: info
    securePort: 7443
    webhookServerPort: 9443
    leaderElect: true

  env:
    wardenImage: hub.c.163.com/kubecube/warden:v1.0.0
    wardenInitImage: hub.c.163.com/kubecube/warden-init:v1.0.0
    pivotCubeSvc: kubecube.kubecube-system:7443
    pivotCubeHost: "Cg=="
    jwtSecret: "56F0D8DB90241C6E"

webhook:
  caBundle: "Cg=="

tlsSecret:
  key: "Cg=="
  crt: "Cg=="

caSecret:
  key: "Cg=="
  crt: "Cg=="

pivotCluster:
  kubernetesAPIEndpoint: "Cg=="
  kubeconfig: "Cg=="

auth:
  github:
    enabled: false
    clientId: ""
    clientSecret: ""

