global:
  dependencesEnable:
    hnc: "true"

  # kubecube hub config
  hub:
    registry: hub.c.163.com
    project: kubecube
    username: kubecube
    password: XXX
    email: kubecube@163.com

  images:
    hnc: hnc/hnc-manager:v1.0.0

# hnc/deployment.yaml
nodeSelector: { }
affinity: { }
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
manager:
  args:
    managedLabel1: kubecube.hnc.x-k8s.io/tenant
    managedLabel2: kubecube.hnc.x-k8s.io/project
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 150Mi