global:
  dependencesEnable:
    ingressController: "true"

  # kubecube hub config
  hub:
    registry: hub.c.163.com
    project: kubecube
    username: kubecube
    password: XXX
    email: kubecube@163.com

  images:
    ingressController: ingress-nginx/controller:v0.46.0-m
    ingressControllerJob: jettech/kube-webhook-certgen:v1.5.1-m

## ingress-controller/deployment.yaml
#controller:
## ingress-controller/job.yaml
#job: