{{- if eq .Values.global.componentsEnable.warden "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfigs
  namespace: {{ template "kubecube.namespace" . }}
type: Opaque
data:
  localCluster: {{ .Values.warden.kubeconfigSecret.localCluster }}
  pivotCluster: {{ .Values.warden.kubeconfigSecret.pivotCluster }}
---
{{- end }}