{{- if eq .Values.global.dependencesEnable.ingressController "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
---
{{- end }}