{{- if eq .Values.global.componentsEnable.webconsole "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webconsole
  namespace: {{ template "kubecube.namespace" . }}
  labels:
    kubecube.io/app: kubecube-webconsole
spec:
  replicas: {{ .Values.webconsole.replicas }}
  selector:
    matchLabels:
      kubecube.io/app: kubecube-webconsole
  template:
    metadata:
      labels:
        kubecube.io/app: kubecube-webconsole
        app: webconsole
    spec:
      {{- with .Values.webconsole.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webconsole.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webconsole.tolerations}}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: JWT_SECRET
              value: 56F0D8DB90241C6E
            - name: KUBECUBE_SVC
              value: https://kubecube-nodeport:7443
          args:
            - --appNamespace={{ template "kubecube.namespace" . }}
            - --log-file=/etc/logs/webconsole.log
            - --max-size={{ .Values.webconsole.args.maxSize }}
            - --max-backups={{ .Values.webconsole.args.maxBackups }}
            - --max-age={{ .Values.webconsole.args.maxAge }}
            - --compress={{ .Values.webconsole.args.compress }}
            - --log-level={{ .Values.webconsole.args.logLevel }}
            - --json-encode={{ .Values.webconsole.args.jsonEncode }}
            - --stacktrace-level={{ .Values.webconsole.args.stacktraceLevel }}
          name: kubecube-webconsole
          image: "{{ .Values.global.hub.registry }}/{{ .Values.global.hub.project }}/{{ .Values.global.images.webconsole }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9081
          resources:
          {{- toYaml .Values.webconsole.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /leader
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: logs
              mountPath: "/etc/logs"
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: logs
          hostPath:
            path: "{{ .Values.global.dataDir }}/log/webconsole"
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
---
{{- end }}