{{- if eq .Values.global.componentsEnable.kubecube "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecube
  namespace: kubecube-system
  labels:
    kubecube.io/app: kubecube
spec:
  replicas: {{ .Values.kubecube.replicas }}
  selector:
    matchLabels:
      kubecube.io/app: kubecube
  template:
    metadata:
      labels:
        kubecube.io/app: kubecube
    spec:
      {{- with .Values.kubecube.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecube.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecube.tolerations}}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kubecube
          image: {{ .Values.kubecube.image.repository}}:{{ .Values.kubecube.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.kubecube.image.pullPolicy }}
          resources:
          {{- toYaml .Values.kubecube.resources | nindent 12 }}
          args:
            - -log-level={{ .Values.kubecube.args.logLevel }}
            - -secure-port={{ .Values.kubecube.args.securePort }}
            - -tls-cert=/etc/tls/tls.crt
            - -tls-key=/etc/tls/tls.key
            - -webhook-cert=/etc/tls
            - -webhook-server-port={{ .Values.kubecube.args.webhookServerPort }}
            - -leader-elect={{ .Values.kubecube.args.leaderElect }}
          env:
            - name: WARDEN_IMAGE
              value: {{ .Values.kubecube.env.wardenImage }}
            - name: WARDEN_INIT_IMAGE
              value: {{ .Values.kubecube.env.wardenInitImage }}
            - name: PIVOT_CUBE_CLUSTER_IP_SVC
              value: {{ .Values.kubecube.env.pivotCubeSvc }}
            - name: PIVOT_CUBE_HOST
              value: {{ .Values.kubecube.env.pivotCubeHost }}
            - name: JWT_SECRET
              value: {{ .Values.kubecube.env.jwtSecret }}
            - name: DEPENDENCE_JOB_IMAGE
              value: {{ .Values.kubecube.env.dependenceJobImage }}
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: cube-tls
              mountPath: "/etc/tls"
              readOnly: true
            - name: logs
              mountPath: "/etc/logs/cube"
            - name: helm-pkg
              mountPath: "/root/helmchartpkg"
            - name: localtime
              mountPath: /etc/localtime
            - mountPath: /i18n
              name: i18n-config
      volumes:
        - name: cube-tls
          secret:
            secretName: cube-tls-secret
        - name: helm-pkg
          hostPath:
            path: /etc/cube/helm-pkg
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: /etc/cube/logs
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
        - configMap:
            defaultMode: 420
            items:
              - key: en.toml
                path: en.toml
              - key: zh.toml
                path: zh.toml
            name: kubecube-language-config
          name: i18n-config
---
{{- end }}
