{{- if eq .Values.global.componentsEnable.kubecube "true" }}
apiVersion: hotplug.kubecube.io/v1
kind: Hotplug
metadata:
  annotations:
    kubecube.io/sync: "true"
  name: common
spec:
  component:
    - name: audit
      status: disabled
    - name: logseer
      namespace: logseer
      pkgName: logseer-v1.0.0.tgz
      status: disabled
    - env: |
        clustername: "{{.cluster}}"
      name: logagent
      namespace: logagent
      pkgName: logagent-v1.0.0.tgz
      status: disabled
    - name: elasticsearch
      namespace: elasticsearch
      pkgName: elasticsearch-7.8.1.tgz
      status: enabled
    - env: |
        grafana:
          enabled: false
        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: "{{.cluster}}"
            remoteWrite:
            - url: {{- if eq .Values.global.componentsEnable.kubecube "true" }}
      name: kubecube-monitoring
      namespace: kubecube-monitoring
      pkgName: kubecube-monitoring-15.4.12.tgz
      status: enabled
    - name: kubecube-thanos
      namespace: kubecube-monitoring
      pkgName: thanos-3.18.0.tgz
      status: disabled
---
apiVersion: hotplug.kubecube.io/v1
kind: Hotplug
metadata:
  annotations:
    kubecube.io/sync: "true"
  name: pivot-cluster
spec:
  component:
    - name: logseer
      status: disabled
    - env: |
        grafana:
          enabled: true
        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: "{{.cluster}}"
            remoteWrite:
            - url: http://kubecube-thanos-receive:19291/api/v1/receive
      name: kubecube-monitoring
    - env: |
        receive:
          tsdbRetention: 7d
          replicaCount: 1
          replicationFactor: 1
      name: kubecube-thanos
      status: enabled
---
{{- end }}